services:
  - type: web
    name: mpasas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: MPASAS_DATA_DIR
        value: /opt/render/project/src/instance
      - key: MPASAS_UPLOAD_DIR
        value: /opt/render/project/src/uploads
      - key: MPASAS_RESULTS_DIR
        value: /opt/render/project/src/results
